version: '2'
services: 
	web:
		build: .
		command: npm run dev
		volumes: 
			- .:/usr/app
			- /usr/app/node_modules
    ports:
        - 3000:3000
    links:
        - mongodb
    depends_on:
        - mongodb
mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/backend
    volumes:
      - ./backend:/backend
    ports:
        - 27017:27017
    command: node backend/server.js # --quiet
